apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mltlu54xj-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mltlu54xj-dotnet-basic-gitops